env:
  node: true
  es6: true
extends: ["eslint:recommended", "plugin:flowtype/recommended"]
globals:
  console: true
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
  ecmaFeatures:
    experimentalObjectRestSpread: true
plugins: ["flowtype"]
rules:
  flowtype/generic-spacing: "off"
  indent: "off"
  linebreak-style: ["error", "unix"]
  no-unused-vars: ["error", {"args": "none"}]
  quotes: "off"
  semi: "off"
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: false
